// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/database64128/proxy-sharing-go/ent/account"
	"github.com/database64128/proxy-sharing-go/ent/predicate"
	"github.com/database64128/proxy-sharing-go/ent/registrationtoken"
)

// RegistrationTokenQuery is the builder for querying RegistrationToken entities.
type RegistrationTokenQuery struct {
	config
	ctx               *QueryContext
	order             []registrationtoken.OrderOption
	inters            []Interceptor
	predicates        []predicate.RegistrationToken
	withRegistrations *AccountQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RegistrationTokenQuery builder.
func (rtq *RegistrationTokenQuery) Where(ps ...predicate.RegistrationToken) *RegistrationTokenQuery {
	rtq.predicates = append(rtq.predicates, ps...)
	return rtq
}

// Limit the number of records to be returned by this query.
func (rtq *RegistrationTokenQuery) Limit(limit int) *RegistrationTokenQuery {
	rtq.ctx.Limit = &limit
	return rtq
}

// Offset to start from.
func (rtq *RegistrationTokenQuery) Offset(offset int) *RegistrationTokenQuery {
	rtq.ctx.Offset = &offset
	return rtq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rtq *RegistrationTokenQuery) Unique(unique bool) *RegistrationTokenQuery {
	rtq.ctx.Unique = &unique
	return rtq
}

// Order specifies how the records should be ordered.
func (rtq *RegistrationTokenQuery) Order(o ...registrationtoken.OrderOption) *RegistrationTokenQuery {
	rtq.order = append(rtq.order, o...)
	return rtq
}

// QueryRegistrations chains the current query on the "registrations" edge.
func (rtq *RegistrationTokenQuery) QueryRegistrations() *AccountQuery {
	query := (&AccountClient{config: rtq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rtq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rtq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(registrationtoken.Table, registrationtoken.FieldID, selector),
			sqlgraph.To(account.Table, account.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, registrationtoken.RegistrationsTable, registrationtoken.RegistrationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(rtq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RegistrationToken entity from the query.
// Returns a *NotFoundError when no RegistrationToken was found.
func (rtq *RegistrationTokenQuery) First(ctx context.Context) (*RegistrationToken, error) {
	nodes, err := rtq.Limit(1).All(setContextOp(ctx, rtq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{registrationtoken.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rtq *RegistrationTokenQuery) FirstX(ctx context.Context) *RegistrationToken {
	node, err := rtq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RegistrationToken ID from the query.
// Returns a *NotFoundError when no RegistrationToken ID was found.
func (rtq *RegistrationTokenQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rtq.Limit(1).IDs(setContextOp(ctx, rtq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{registrationtoken.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rtq *RegistrationTokenQuery) FirstIDX(ctx context.Context) int {
	id, err := rtq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RegistrationToken entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RegistrationToken entity is found.
// Returns a *NotFoundError when no RegistrationToken entities are found.
func (rtq *RegistrationTokenQuery) Only(ctx context.Context) (*RegistrationToken, error) {
	nodes, err := rtq.Limit(2).All(setContextOp(ctx, rtq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{registrationtoken.Label}
	default:
		return nil, &NotSingularError{registrationtoken.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rtq *RegistrationTokenQuery) OnlyX(ctx context.Context) *RegistrationToken {
	node, err := rtq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RegistrationToken ID in the query.
// Returns a *NotSingularError when more than one RegistrationToken ID is found.
// Returns a *NotFoundError when no entities are found.
func (rtq *RegistrationTokenQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rtq.Limit(2).IDs(setContextOp(ctx, rtq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{registrationtoken.Label}
	default:
		err = &NotSingularError{registrationtoken.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rtq *RegistrationTokenQuery) OnlyIDX(ctx context.Context) int {
	id, err := rtq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RegistrationTokens.
func (rtq *RegistrationTokenQuery) All(ctx context.Context) ([]*RegistrationToken, error) {
	ctx = setContextOp(ctx, rtq.ctx, "All")
	if err := rtq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RegistrationToken, *RegistrationTokenQuery]()
	return withInterceptors[[]*RegistrationToken](ctx, rtq, qr, rtq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rtq *RegistrationTokenQuery) AllX(ctx context.Context) []*RegistrationToken {
	nodes, err := rtq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RegistrationToken IDs.
func (rtq *RegistrationTokenQuery) IDs(ctx context.Context) (ids []int, err error) {
	if rtq.ctx.Unique == nil && rtq.path != nil {
		rtq.Unique(true)
	}
	ctx = setContextOp(ctx, rtq.ctx, "IDs")
	if err = rtq.Select(registrationtoken.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rtq *RegistrationTokenQuery) IDsX(ctx context.Context) []int {
	ids, err := rtq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rtq *RegistrationTokenQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rtq.ctx, "Count")
	if err := rtq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rtq, querierCount[*RegistrationTokenQuery](), rtq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rtq *RegistrationTokenQuery) CountX(ctx context.Context) int {
	count, err := rtq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rtq *RegistrationTokenQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rtq.ctx, "Exist")
	switch _, err := rtq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rtq *RegistrationTokenQuery) ExistX(ctx context.Context) bool {
	exist, err := rtq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RegistrationTokenQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rtq *RegistrationTokenQuery) Clone() *RegistrationTokenQuery {
	if rtq == nil {
		return nil
	}
	return &RegistrationTokenQuery{
		config:            rtq.config,
		ctx:               rtq.ctx.Clone(),
		order:             append([]registrationtoken.OrderOption{}, rtq.order...),
		inters:            append([]Interceptor{}, rtq.inters...),
		predicates:        append([]predicate.RegistrationToken{}, rtq.predicates...),
		withRegistrations: rtq.withRegistrations.Clone(),
		// clone intermediate query.
		sql:  rtq.sql.Clone(),
		path: rtq.path,
	}
}

// WithRegistrations tells the query-builder to eager-load the nodes that are connected to
// the "registrations" edge. The optional arguments are used to configure the query builder of the edge.
func (rtq *RegistrationTokenQuery) WithRegistrations(opts ...func(*AccountQuery)) *RegistrationTokenQuery {
	query := (&AccountClient{config: rtq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rtq.withRegistrations = query
	return rtq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RegistrationToken.Query().
//		GroupBy(registrationtoken.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rtq *RegistrationTokenQuery) GroupBy(field string, fields ...string) *RegistrationTokenGroupBy {
	rtq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RegistrationTokenGroupBy{build: rtq}
	grbuild.flds = &rtq.ctx.Fields
	grbuild.label = registrationtoken.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.RegistrationToken.Query().
//		Select(registrationtoken.FieldCreateTime).
//		Scan(ctx, &v)
func (rtq *RegistrationTokenQuery) Select(fields ...string) *RegistrationTokenSelect {
	rtq.ctx.Fields = append(rtq.ctx.Fields, fields...)
	sbuild := &RegistrationTokenSelect{RegistrationTokenQuery: rtq}
	sbuild.label = registrationtoken.Label
	sbuild.flds, sbuild.scan = &rtq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RegistrationTokenSelect configured with the given aggregations.
func (rtq *RegistrationTokenQuery) Aggregate(fns ...AggregateFunc) *RegistrationTokenSelect {
	return rtq.Select().Aggregate(fns...)
}

func (rtq *RegistrationTokenQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rtq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rtq); err != nil {
				return err
			}
		}
	}
	for _, f := range rtq.ctx.Fields {
		if !registrationtoken.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rtq.path != nil {
		prev, err := rtq.path(ctx)
		if err != nil {
			return err
		}
		rtq.sql = prev
	}
	return nil
}

func (rtq *RegistrationTokenQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RegistrationToken, error) {
	var (
		nodes       = []*RegistrationToken{}
		_spec       = rtq.querySpec()
		loadedTypes = [1]bool{
			rtq.withRegistrations != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RegistrationToken).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RegistrationToken{config: rtq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rtq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rtq.withRegistrations; query != nil {
		if err := rtq.loadRegistrations(ctx, query, nodes,
			func(n *RegistrationToken) { n.Edges.Registrations = []*Account{} },
			func(n *RegistrationToken, e *Account) { n.Edges.Registrations = append(n.Edges.Registrations, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rtq *RegistrationTokenQuery) loadRegistrations(ctx context.Context, query *AccountQuery, nodes []*RegistrationToken, init func(*RegistrationToken), assign func(*RegistrationToken, *Account)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*RegistrationToken)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Account(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(registrationtoken.RegistrationsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.registration_token_registrations
		if fk == nil {
			return fmt.Errorf(`foreign-key "registration_token_registrations" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "registration_token_registrations" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (rtq *RegistrationTokenQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rtq.querySpec()
	_spec.Node.Columns = rtq.ctx.Fields
	if len(rtq.ctx.Fields) > 0 {
		_spec.Unique = rtq.ctx.Unique != nil && *rtq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rtq.driver, _spec)
}

func (rtq *RegistrationTokenQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(registrationtoken.Table, registrationtoken.Columns, sqlgraph.NewFieldSpec(registrationtoken.FieldID, field.TypeInt))
	_spec.From = rtq.sql
	if unique := rtq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rtq.path != nil {
		_spec.Unique = true
	}
	if fields := rtq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, registrationtoken.FieldID)
		for i := range fields {
			if fields[i] != registrationtoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rtq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rtq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rtq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rtq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rtq *RegistrationTokenQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rtq.driver.Dialect())
	t1 := builder.Table(registrationtoken.Table)
	columns := rtq.ctx.Fields
	if len(columns) == 0 {
		columns = registrationtoken.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rtq.sql != nil {
		selector = rtq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rtq.ctx.Unique != nil && *rtq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rtq.predicates {
		p(selector)
	}
	for _, p := range rtq.order {
		p(selector)
	}
	if offset := rtq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rtq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RegistrationTokenGroupBy is the group-by builder for RegistrationToken entities.
type RegistrationTokenGroupBy struct {
	selector
	build *RegistrationTokenQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rtgb *RegistrationTokenGroupBy) Aggregate(fns ...AggregateFunc) *RegistrationTokenGroupBy {
	rtgb.fns = append(rtgb.fns, fns...)
	return rtgb
}

// Scan applies the selector query and scans the result into the given value.
func (rtgb *RegistrationTokenGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rtgb.build.ctx, "GroupBy")
	if err := rtgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RegistrationTokenQuery, *RegistrationTokenGroupBy](ctx, rtgb.build, rtgb, rtgb.build.inters, v)
}

func (rtgb *RegistrationTokenGroupBy) sqlScan(ctx context.Context, root *RegistrationTokenQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rtgb.fns))
	for _, fn := range rtgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rtgb.flds)+len(rtgb.fns))
		for _, f := range *rtgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rtgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rtgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RegistrationTokenSelect is the builder for selecting fields of RegistrationToken entities.
type RegistrationTokenSelect struct {
	*RegistrationTokenQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rts *RegistrationTokenSelect) Aggregate(fns ...AggregateFunc) *RegistrationTokenSelect {
	rts.fns = append(rts.fns, fns...)
	return rts
}

// Scan applies the selector query and scans the result into the given value.
func (rts *RegistrationTokenSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rts.ctx, "Select")
	if err := rts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RegistrationTokenQuery, *RegistrationTokenSelect](ctx, rts.RegistrationTokenQuery, rts, rts.inters, v)
}

func (rts *RegistrationTokenSelect) sqlScan(ctx context.Context, root *RegistrationTokenQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rts.fns))
	for _, fn := range rts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
