// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// Node is the predicate function for node builders.
type Node func(*sql.Selector)

// Server is the predicate function for server builders.
type Server func(*sql.Selector)
